In [12]:
import numpy as np
import tensorflow
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

In [2]:
import keras

In [56]:
data1=[[i for i in range (0,100)]]

In [58]:
data1=np.array(data1,dtype=float)

In [59]:
type(data1)

numpy.ndarray

In [60]:
target1=[[i for i in range(1,101)]]
target1=np.array(target1,dtype=float)
type(target1)

numpy.ndarray

In [61]:
data1=data1.reshape(1,1,100)
target1=target1.reshape(1,1,100)

In [62]:
data1


array([[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,
         12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.,
         24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
         36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47.,
         48., 49., 50., 51., 52., 53., 54., 55., 56., 57., 58., 59.,
         60., 61., 62., 63., 64., 65., 66., 67., 68., 69., 70., 71.,
         72., 73., 74., 75., 76., 77., 78., 79., 80., 81., 82., 83.,
         84., 85., 86., 87., 88., 89., 90., 91., 92., 93., 94., 95.,
         96., 97., 98., 99.]]])

In [63]:
test_x=[[i for i in range(100,200)]]
test_x=np.array(test_x,dtype=float)
type(test_x)

numpy.ndarray

In [66]:
test_y=[[i for i in range(200,300)]]
test_y=np.array(test_y)
type(test_y)

numpy.ndarray

In [67]:
model=Sequential()

In [68]:
test_x=test_x.reshape(1,1,100)
test_y=test_y.reshape(1,1,100)

In [69]:
model.add(LSTM(100,input_shape=(1,100),return_sequences=True))
model.add(Dense(100))

In [70]:
model.compile(loss='mean_absolute_error', optimizer='adam', metrics='accuracy')

In [72]:
model.fit(data1,target1,epochs=30,batch_size=1,verbose=2,validation_data=(test_x,test_y)) # Usually we should give 1000 epochs

Epoch 1/30
1/1 - 0s - loss: 49.7080 - accuracy: 0.0000e+00 - val_loss: 248.8293 - val_accuracy: 0.0000e+00
Epoch 2/30
1/1 - 0s - loss: 49.6840 - accuracy: 0.0000e+00 - val_loss: 248.8096 - val_accuracy: 0.0000e+00
Epoch 3/30
1/1 - 0s - loss: 49.6601 - accuracy: 0.0000e+00 - val_loss: 248.7900 - val_accuracy: 0.0000e+00
Epoch 4/30
1/1 - 0s - loss: 49.6361 - accuracy: 0.0000e+00 - val_loss: 248.7704 - val_accuracy: 0.0000e+00
Epoch 5/30
1/1 - 0s - loss: 49.6121 - accuracy: 0.0000e+00 - val_loss: 248.7509 - val_accuracy: 0.0000e+00
Epoch 6/30
1/1 - 0s - loss: 49.5880 - accuracy: 0.0000e+00 - val_loss: 248.7314 - val_accuracy: 0.0000e+00
Epoch 7/30
1/1 - 0s - loss: 49.5639 - accuracy: 0.0000e+00 - val_loss: 248.7118 - val_accuracy: 0.0000e+00
Epoch 8/30
1/1 - 0s - loss: 49.5398 - accuracy: 0.0000e+00 - val_loss: 248.6923 - val_accuracy: 0.0000e+00
Epoch 9/30
1/1 - 0s - loss: 49.5156 - accuracy: 0.0000e+00 - val_loss: 248.6729 - val_accuracy: 0.0000e+00
Epoch 10/30
1/1 - 0s - loss: 49.4915 

In [54]:
data1

array([[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,
         12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.,
         24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
         36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47.,
         48., 49., 50., 51., 52., 53., 54., 55., 56., 57., 58., 59.,
         60., 61., 62., 63., 64., 65., 66., 67., 68., 69., 70., 71.,
         72., 73., 74., 75., 76., 77., 78., 79., 80., 81., 82., 83.,
         84., 85., 86., 87., 88., 89., 90., 91., 92., 93., 94., 95.,
         96., 97., 98., 99.]]])

In [55]:
target1

array([[[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
          11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,
          21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,
          31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,
          41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,
          51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,
          61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,
          71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,
          81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,
          91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]]])